title: Praveen's Automotive AI Blog
description: Data Science, SciML/PINN, Reinforcement Learning, Automotive AI
theme: minima

minima:
  skin: auto
plugins:
  - jekyll-feed
  - jekyll-seo-tag
kramdown:
  math_engine: mathjax
